# Generated by Django 4.2.6 on 2023-10-18 06:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Привычка')),
                ('location', models.CharField(max_length=100, verbose_name='Место выполнения')),
                ('time', models.TimeField(verbose_name='Время выполнения')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('periodicity', models.CharField(choices=[('daily', 'Ежедневно'), ('every_other_day', '1 раз в два дня'), ('every_third_day', '1 раз в три дня'), ('every_fourth_day', '1 раз в четыре дня'), ('every_fifth_day', '1 раз в пять дней'), ('every_sixth_day', '1 раз в шесть дней'), ('weekly', 'Еженедельно')], max_length=50, verbose_name='Периодичность')),
                ('days', models.PositiveIntegerField(verbose_name='Период в днях')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
                ('last_completed', models.DateTimeField(blank=True, null=True, verbose_name='Последнее выполнение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
                'db_table': 'habits',
            },
        ),
    ]
