# Generated by Django 4.2.6 on 2023-10-21 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='День начала привычки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(max_length=50, verbose_name='Периодичность'),
        ),
    ]
