# Generated by Django 4.2.6 on 2023-10-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_start_date_alter_habit_periodicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='last_completed',
        ),
        migrations.AddField(
            model_name='habit',
            name='last_notification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего уведомления'),
        ),
    ]
