# Generated by Django 4.2.6 on 2023-10-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_habit_last_completed_habit_last_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_notification',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего уведомления'),
        ),
    ]
