# Generated by Django 4.2.6 on 2023-11-09 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0005_alter_habit_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='days',
            field=models.PositiveIntegerField(verbose_name='Days of period'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Execution time'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='Pleasant habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='last_notification',
            field=models.DateField(blank=True, null=True, verbose_name='Last notification date'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(max_length=50, verbose_name='Periodicity'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Related habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reward'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='Time of execution'),
        ),
    ]
